title: "Sound recording and Music sound separation project"
description: "Description courte"
url: "https://sourceseparation2025-2026.github.io"
baseurl: "/LASS_PAM"  # Important ! Nom de votre repo
remote_theme: mmistakes/minimal-mistakes

# Navigation
masthead_title: "LASS PAM"
minimal_mistakes_skin: "default"

# Menu principal
navigation:
  - title: "Photos"
    url: /photo
  - title: "Audio files"
    url: /audio
  - title: "Test"
    url: /test

# Auteur
author:
  name: "Loïs Guerci, Louis Gosselin, Samy Benzaïm, Antonin Longeot, Jean-Henri Nothias"
  email: "guerci@ircam.fr"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/loguerci/LASS_PAM"